### ISSUE TITLE
Add icon seems to be blank

### ISSUE THREAD

**Issue by Shadowblitz16** [Xrayez/godot-editor-icons-previewer#1]
```
func _ready():
	$Header/Value.icon = get_icon('Add', 'EditorIcons')
```

seems to return a blank icon

**Comment by Xrayez** [comment]
See updated README. 🙂

In short, this is meant to be used in editor plugins. Plain `tool` scripts require more sophisticated approach, but relies on internal `EditorNode`. And this won't work in a game/exported projects.

Here's a shorter version:
```gdscript
tool
extends Node2D

func _draw():
	if Engine.editor_hint:
		var editor_gui_base = get_tree().get_root().get_child(0).get_gui_base()
		draw_texture(editor_gui_base.get_icon('Add', 'EditorIcons'), Vector2())
```

**Comment by Shadowblitz16** [comment]
ok ty

**Comment by Shadowblitz16** [comment]
@Xrayez wait do I have to draw the node or can I just set it?

**Comment by Xrayez** [comment]
@Shadowblitz16 the snippet above is just an easy way to showcase the feature, `Control.get_icon()` returns a texture, so this can be used everywhere where `Texture` resource is accepted. This includes `draw_texture()` above and things like `$Button.icon`, or even `$Sprite.texture`.

**Comment by Shadowblitz16** [comment]
@Xrayez  I was just wondering because it still doesn't seem to work

**Comment by Xrayez** [comment]
@Shadowblitz16 try this minimal project [editor_icon_in_tool_script.zip](https://github.com/Xrayez/godot-editor-icons-previewer/files/5611363/editor_icon_in_tool_script.zip), this should work in editor:

![image](https://user-images.githubusercontent.com/17108460/100528120-d07a2300-31e1-11eb-8879-463fd9b3f3dd.png)

Perhaps we have a misunderstanding here. If you run a project from within the editor, this is expected that this won't work, this only works directly in the editor. 😛

And this functionality is not dependent on the plugin in either case.

If this doesn't work in the editor when you switch to 2D tab, then that's indeed a bug. If so, then please provide exact Godot version you're using to debug this further.
