### ISSUE TITLE
Port to 4.0

### ISSUE THREAD

**Issue by KoBeWi** [Xrayez/godot-editor-icons-previewer#2]
I needed this in 4.0, so did some initial port:
[editor_icon_previewer.zip](https://github.com/Xrayez/godot-editor-icons-previewer/files/8459829/editor_icon_previewer.zip)

Not everything works, but it does the job at least:
![image](https://user-images.githubusercontent.com/2223172/162637985-01eb7df6-3dfc-4aa7-9f8f-ad26b4c124e5.png)

**Comment by Xrayez** [comment]
Thanks, I created a new `gd4` branch (also renamed `master` to `gd3`), feel free to create a PR for `gd4` branch if you wish. 🙂

**Comment by Dark-Peace** [comment]
Oh, well. I spent hours porting it abd someone already done it. I added some features along the way though.
I opened a pull request.

**Comment by Xrayez** [comment]
Closed via #5.
